# -*- coding: utf-8 -*-
#  Copyright (c) 2022 Mica. All rights reserved. All software, including, without limitation, all source 
#  code and object code, is the intellectual property of Mica, Inc. and is protected by copyright, trademark and 
#  other intellectual property laws (collective "Mica Software"). You may not use, copy, reproduce, download, store, 
#  post, broadcast, transmit, modify, sell or make available to the public content from the Mica Software without a 
#  valid license or the prior written approval of Mica, Inc. Mica, its logos, slogans, taglines, 
#  products, feature names, and other trademarks are trademarks of Mica, Inc. and may not be used without 
#  permission.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/enums/unit/v1/unit.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63ommon/enums/unit/v1/unit.proto\x12\x14\x63ommon.enums.unit.v1*\xbf\x02\n\x04Unit\x12\x14\n\x10UNIT_UNSPECIFIED\x10\x00\x12\r\n\tUNIT_ITEM\x10\x01\x12\r\n\tUNIT_GRAM\x10\x02\x12\x11\n\rUNIT_KILOGRAM\x10\x03\x12\x0e\n\nUNIT_POUND\x10\x04\x12\x0e\n\nUNIT_OUNCE\x10\x05\x12\x0e\n\nUNIT_LITRE\x10\x06\x12\x13\n\x0fUNIT_MILLILITRE\x10\x07\x12\x0f\n\x0bUNIT_GALLON\x10\x08\x12\x0e\n\nUNIT_QUART\x10\t\x12\r\n\tUNIT_PINT\x10\n\x12\x14\n\x10UNIT_FLUID_OUNCE\x10\x0b\x12\x0e\n\nUNIT_METRE\x10\x0c\x12\x13\n\x0fUNIT_CENTIMETRE\x10\r\x12\x13\n\x0fUNIT_MILLIMETRE\x10\x0e\x12\r\n\tUNIT_YARD\x10\x0f\x12\r\n\tUNIT_FOOT\x10\x10\x12\r\n\tUNIT_INCH\x10\x11\x42O\n\x17io.mica.common.enums.v1B\rUnitEnumProtoZ\x1emica/proto/common/enums/unitv1\xa2\x02\x04MICAb\x06proto3')

_UNIT = DESCRIPTOR.enum_types_by_name['Unit']
Unit = enum_type_wrapper.EnumTypeWrapper(_UNIT)
UNIT_UNSPECIFIED = 0
UNIT_ITEM = 1
UNIT_GRAM = 2
UNIT_KILOGRAM = 3
UNIT_POUND = 4
UNIT_OUNCE = 5
UNIT_LITRE = 6
UNIT_MILLILITRE = 7
UNIT_GALLON = 8
UNIT_QUART = 9
UNIT_PINT = 10
UNIT_FLUID_OUNCE = 11
UNIT_METRE = 12
UNIT_CENTIMETRE = 13
UNIT_MILLIMETRE = 14
UNIT_YARD = 15
UNIT_FOOT = 16
UNIT_INCH = 17


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027io.mica.common.enums.v1B\rUnitEnumProtoZ\036mica/proto/common/enums/unitv1\242\002\004MICA'
  _UNIT._serialized_start=58
  _UNIT._serialized_end=377
# @@protoc_insertion_point(module_scope)
