# -*- coding: utf-8 -*-
#  Copyright (c) 2023 Mica. All rights reserved. All software, including, without limitation, all source
#  code and object code, is the intellectual property of Mica, Inc. and is protected by copyright, trademark and
#  other intellectual property laws (collective "Mica Software"). You may not use, copy, reproduce, download, store,
#  post, broadcast, transmit, modify, sell or make available to the public content from the Mica Software without a
#  valid license or the prior written approval of Mica, Inc. Mica, its logos, slogans, taglines,
#  products, feature names, and other trademarks are trademarks of Mica, Inc. and may not be used without
#  permission.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: micashared/common/v1/address.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from serviceprovider.micashared.common.enums.country.v1 import country_pb2 as micashared_dot_common_dot_enums_dot_country_dot_v1_dot_country__pb2
from serviceprovider.micashared.common.enums.region.v1 import region_pb2 as micashared_dot_common_dot_enums_dot_region_dot_v1_dot_region__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"micashared/common/v1/address.proto\x12\x14micashared.common.v1\x1a\x30micashared/common/enums/country/v1/country.proto\x1a.micashared/common/enums/region/v1/region.proto\"\xbf\x01\n\x07\x41\x64\x64ress\x12\x14\n\x0cstreet_lines\x18\x01 \x03(\t\x12\x10\n\x08locality\x18\x02 \x01(\t\x12\x39\n\x06region\x18\x03 \x01(\x0e\x32).micashared.common.enums.region.v1.Region\x12\x13\n\x0bpostal_code\x18\x04 \x01(\t\x12<\n\x07\x63ountry\x18\x05 \x01(\x0e\x32+.micashared.common.enums.country.v1.CountryBM\n\x17io.micashared.common.v1B\x0c\x41\x64\x64ressProtoZ\x1dmicashared/common/v1;commonv1\xa2\x02\x04MICAb\x06proto3')



_ADDRESS = DESCRIPTOR.message_types_by_name['Address']
Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'micashared.common.v1.address_pb2'
  # @@protoc_insertion_point(class_scope:micashared.common.v1.Address)
  })
_sym_db.RegisterMessage(Address)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027io.micashared.common.v1B\014AddressProtoZ\035micashared/common/v1;commonv1\242\002\004MICA'
  _ADDRESS._serialized_start=159
  _ADDRESS._serialized_end=350
# @@protoc_insertion_point(module_scope)
