# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/enums/serviceproviderstatus/v1/service_provider_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/enums/serviceproviderstatus/v1/service_provider_status.proto',
  package='common.enums.serviceproviderstatus.v1',
  syntax='proto3',
  serialized_options=b'\n\035network.ten80.common.enums.v1B\036ServiceProviderStatusEnumProtoZ0ten80/proto/common/enums/serviceproviderstatusv1\242\002\005TEN80',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nCcommon/enums/serviceproviderstatus/v1/service_provider_status.proto\x12%common.enums.serviceproviderstatus.v1*\x8a\x01\n\x15ServiceProviderStatus\x12\'\n#SERVICE_PROVIDER_STATUS_UNSPECIFIED\x10\x00\x12\"\n\x1eSERVICE_PROVIDER_STATUS_ACTIVE\x10\x01\x12$\n SERVICE_PROVIDER_STATUS_INACTIVE\x10\x02\x42y\n\x1dnetwork.ten80.common.enums.v1B\x1eServiceProviderStatusEnumProtoZ0ten80/proto/common/enums/serviceproviderstatusv1\xa2\x02\x05TEN80b\x06proto3'
)

_SERVICEPROVIDERSTATUS = _descriptor.EnumDescriptor(
  name='ServiceProviderStatus',
  full_name='common.enums.serviceproviderstatus.v1.ServiceProviderStatus',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SERVICE_PROVIDER_STATUS_UNSPECIFIED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SERVICE_PROVIDER_STATUS_ACTIVE', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SERVICE_PROVIDER_STATUS_INACTIVE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=111,
  serialized_end=249,
)
_sym_db.RegisterEnumDescriptor(_SERVICEPROVIDERSTATUS)

ServiceProviderStatus = enum_type_wrapper.EnumTypeWrapper(_SERVICEPROVIDERSTATUS)
SERVICE_PROVIDER_STATUS_UNSPECIFIED = 0
SERVICE_PROVIDER_STATUS_ACTIVE = 1
SERVICE_PROVIDER_STATUS_INACTIVE = 2


DESCRIPTOR.enum_types_by_name['ServiceProviderStatus'] = _SERVICEPROVIDERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
