# -*- coding: utf-8 -*-
#  Copyright (c) 2022 Mica. All rights reserved. All software, including, without limitation, all source 
#  code and object code, is the intellectual property of Mica, Inc. and is protected by copyright, trademark and 
#  other intellectual property laws (collective "Mica Software"). You may not use, copy, reproduce, download, store, 
#  post, broadcast, transmit, modify, sell or make available to the public content from the Mica Software without a 
#  valid license or the prior written approval of Mica, Inc. Mica, its logos, slogans, taglines, 
#  products, feature names, and other trademarks are trademarks of Mica, Inc. and may not be used without 
#  permission.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discount/service/v1/discount_service_test_support.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from micadiscount.common.v1 import error_pb2 as common_dot_v1_dot_error__pb2
from micadiscount.common.v1 import line_item_pb2 as common_dot_v1_dot_line__item__pb2
from micadiscount.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7discount/service/v1/discount_service_test_support.proto\x12\x13\x64iscount.service.v1\x1a\x15\x63ommon/v1/error.proto\x1a\x19\x63ommon/v1/line_item.proto\x1a\x17validate/validate.proto\"t\n\x18\x44\x65termineDiscountRequest\x12%\n\x12\x66\x65\x64\x65rated_user_key\x18\x01 \x01(\tB\t\xfa\x42\x06r\x04\x10\x1e\x18\x32\x12\x31\n\nline_items\x18\x02 \x03(\x0b\x32\x13.common.v1.LineItemB\x08\xfa\x42\x05\x92\x01\x02\x08\x01\"\xcb\x01\n\x19\x44\x65termineDiscountResponse\x12\x45\n\x06status\x18\x01 \x01(\x0e\x32\x35.discount.service.v1.DetermineDiscountResponse.Status\x12\x1f\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x10.common.v1.Error\"F\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n\x0eSTATUS_SUCCESS\x10\x01\x12\x10\n\x0cSTATUS_ERROR\x10\x02\"\x16\n\x14\x41pplyDiscountRequest\"\xc3\x01\n\x15\x41pplyDiscountResponse\x12\x41\n\x06status\x18\x01 \x01(\x0e\x32\x31.discount.service.v1.ApplyDiscountResponse.Status\x12\x1f\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x10.common.v1.Error\"F\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n\x0eSTATUS_SUCCESS\x10\x01\x12\x10\n\x0cSTATUS_ERROR\x10\x02\x32\x84\x02\n\x1a\x44iscountTestSupportService\x12x\n\x15TestDetermineDiscount\x12-.discount.service.v1.DetermineDiscountRequest\x1a..discount.service.v1.DetermineDiscountResponse\"\x00\x12l\n\x11TestApplyDiscount\x12).discount.service.v1.ApplyDiscountRequest\x1a*.discount.service.v1.ApplyDiscountResponse\"\x00\x42\x64\n\x1bio.mica.discount.service.v1B\x1f\x44iscountTestSupportServiceProtoZ\x1dmica/proto/discount/servicev1\xa2\x02\x04MICAb\x06proto3')



_DETERMINEDISCOUNTREQUEST = DESCRIPTOR.message_types_by_name['DetermineDiscountRequest']
_DETERMINEDISCOUNTRESPONSE = DESCRIPTOR.message_types_by_name['DetermineDiscountResponse']
_APPLYDISCOUNTREQUEST = DESCRIPTOR.message_types_by_name['ApplyDiscountRequest']
_APPLYDISCOUNTRESPONSE = DESCRIPTOR.message_types_by_name['ApplyDiscountResponse']
_DETERMINEDISCOUNTRESPONSE_STATUS = _DETERMINEDISCOUNTRESPONSE.enum_types_by_name['Status']
_APPLYDISCOUNTRESPONSE_STATUS = _APPLYDISCOUNTRESPONSE.enum_types_by_name['Status']
DetermineDiscountRequest = _reflection.GeneratedProtocolMessageType('DetermineDiscountRequest', (_message.Message,), {
  'DESCRIPTOR' : _DETERMINEDISCOUNTREQUEST,
  '__module__' : 'discount.service.v1.discount_service_test_support_pb2'
  # @@protoc_insertion_point(class_scope:discount.service.v1.DetermineDiscountRequest)
  })
_sym_db.RegisterMessage(DetermineDiscountRequest)

DetermineDiscountResponse = _reflection.GeneratedProtocolMessageType('DetermineDiscountResponse', (_message.Message,), {
  'DESCRIPTOR' : _DETERMINEDISCOUNTRESPONSE,
  '__module__' : 'discount.service.v1.discount_service_test_support_pb2'
  # @@protoc_insertion_point(class_scope:discount.service.v1.DetermineDiscountResponse)
  })
_sym_db.RegisterMessage(DetermineDiscountResponse)

ApplyDiscountRequest = _reflection.GeneratedProtocolMessageType('ApplyDiscountRequest', (_message.Message,), {
  'DESCRIPTOR' : _APPLYDISCOUNTREQUEST,
  '__module__' : 'discount.service.v1.discount_service_test_support_pb2'
  # @@protoc_insertion_point(class_scope:discount.service.v1.ApplyDiscountRequest)
  })
_sym_db.RegisterMessage(ApplyDiscountRequest)

ApplyDiscountResponse = _reflection.GeneratedProtocolMessageType('ApplyDiscountResponse', (_message.Message,), {
  'DESCRIPTOR' : _APPLYDISCOUNTRESPONSE,
  '__module__' : 'discount.service.v1.discount_service_test_support_pb2'
  # @@protoc_insertion_point(class_scope:discount.service.v1.ApplyDiscountResponse)
  })
_sym_db.RegisterMessage(ApplyDiscountResponse)

_DISCOUNTTESTSUPPORTSERVICE = DESCRIPTOR.services_by_name['DiscountTestSupportService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.mica.discount.service.v1B\037DiscountTestSupportServiceProtoZ\035mica/proto/discount/servicev1\242\002\004MICA'
  _DETERMINEDISCOUNTREQUEST.fields_by_name['federated_user_key']._options = None
  _DETERMINEDISCOUNTREQUEST.fields_by_name['federated_user_key']._serialized_options = b'\372B\006r\004\020\036\0302'
  _DETERMINEDISCOUNTREQUEST.fields_by_name['line_items']._options = None
  _DETERMINEDISCOUNTREQUEST.fields_by_name['line_items']._serialized_options = b'\372B\005\222\001\002\010\001'
  _DETERMINEDISCOUNTREQUEST._serialized_start=155
  _DETERMINEDISCOUNTREQUEST._serialized_end=271
  _DETERMINEDISCOUNTRESPONSE._serialized_start=274
  _DETERMINEDISCOUNTRESPONSE._serialized_end=477
  _DETERMINEDISCOUNTRESPONSE_STATUS._serialized_start=407
  _DETERMINEDISCOUNTRESPONSE_STATUS._serialized_end=477
  _APPLYDISCOUNTREQUEST._serialized_start=479
  _APPLYDISCOUNTREQUEST._serialized_end=501
  _APPLYDISCOUNTRESPONSE._serialized_start=504
  _APPLYDISCOUNTRESPONSE._serialized_end=699
  _APPLYDISCOUNTRESPONSE_STATUS._serialized_start=407
  _APPLYDISCOUNTRESPONSE_STATUS._serialized_end=477
  _DISCOUNTTESTSUPPORTSERVICE._serialized_start=702
  _DISCOUNTTESTSUPPORTSERVICE._serialized_end=962
# @@protoc_insertion_point(module_scope)
