# -*- coding: utf-8 -*-
#  Copyright (c) 2022 Mica. All rights reserved. All software, including, without limitation, all source 
#  code and object code, is the intellectual property of Mica, Inc. and is protected by copyright, trademark and 
#  other intellectual property laws (collective "Mica Software"). You may not use, copy, reproduce, download, store, 
#  post, broadcast, transmit, modify, sell or make available to the public content from the Mica Software without a 
#  valid license or the prior written approval of Mica, Inc. Mica, its logos, slogans, taglines, 
#  products, feature names, and other trademarks are trademarks of Mica, Inc. and may not be used without 
#  permission.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discount/service/v1/discount_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from micadiscount.common.ping.v1 import ping_pb2 as common_dot_ping_dot_v1_dot_ping__pb2
from micadiscount.discount.discount.v1 import discount_pb2 as discount_dot_discount_dot_v1_dot_discount__pb2
from micadiscount.discount.discountprovider.v1 import discount_provider_pb2 as discount_dot_discountprovider_dot_v1_dot_discount__provider__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*discount/service/v1/discount_service.proto\x12\x13\x64iscount.service.v1\x1a\x19\x63ommon/ping/v1/ping.proto\x1a#discount/discount/v1/discount.proto\x1a\x34\x64iscount/discountprovider/v1/discount_provider.proto2\xb1\x04\n\x0f\x44iscountService\x12|\n\x13GetDiscountProvider\x12\x30.discount.discount.v1.GetDiscountProviderRequest\x1a\x31.discount.discount.v1.GetDiscountProviderResponse\"\x00\x12\x85\x01\n\x16UpdateDiscountProvider\x12\x33.discount.discount.v1.UpdateDiscountProviderRequest\x1a\x34.discount.discount.v1.UpdateDiscountProviderResponse\"\x00\x12m\n\x0e\x43reateDiscount\x12+.discount.discount.v1.CreateDiscountRequest\x1a,.discount.discount.v1.CreateDiscountResponse\"\x00\x12\x64\n\x0bGetDiscount\x12(.discount.discount.v1.GetDiscountRequest\x1a).discount.discount.v1.GetDiscountResponse\"\x00\x12\x43\n\x04Ping\x12\x1b.common.ping.v1.PingRequest\x1a\x1c.common.ping.v1.PingResponse\"\x00\x42Y\n\x1bio.mica.discount.service.v1B\x14\x44iscountServiceProtoZ\x1dmica/proto/discount/servicev1\xa2\x02\x04MICAb\x06proto3')



_DISCOUNTSERVICE = DESCRIPTOR.services_by_name['DiscountService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.mica.discount.service.v1B\024DiscountServiceProtoZ\035mica/proto/discount/servicev1\242\002\004MICA'
  _DISCOUNTSERVICE._serialized_start=186
  _DISCOUNTSERVICE._serialized_end=747
# @@protoc_insertion_point(module_scope)
