# -*- coding: utf-8 -*-
#  Copyright (c) 2023 Mica. All rights reserved. All software, including, without limitation, all source
#  code and object code, is the intellectual property of Mica, Inc. and is protected by copyright, trademark and
#  other intellectual property laws (collective "Mica Software"). You may not use, copy, reproduce, download, store,
#  post, broadcast, transmit, modify, sell or make available to the public content from the Mica Software without a
#  valid license or the prior written approval of Mica, Inc. Mica, its logos, slogans, taglines,
#  products, feature names, and other trademarks are trademarks of Mica, Inc. and may not be used without
#  permission.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: micashared/common/enums/serviceproviderstatus/v1/service_provider_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nNmicashared/common/enums/serviceproviderstatus/v1/service_provider_status.proto\x12\x30micashared.common.enums.serviceproviderstatus.v1*\x8a\x01\n\x15ServiceProviderStatus\x12\'\n#SERVICE_PROVIDER_STATUS_UNSPECIFIED\x10\x00\x12\"\n\x1eSERVICE_PROVIDER_STATUS_ACTIVE\x10\x01\x12$\n SERVICE_PROVIDER_STATUS_INACTIVE\x10\x02\x42w\n\x1dio.micashared.common.enums.v1B\x1eServiceProviderStatusEnumProtoZ/micashared/common/enums/serviceproviderstatusv1\xa2\x02\x04MICAb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'micashared.common.enums.serviceproviderstatus.v1.service_provider_status_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035io.micashared.common.enums.v1B\036ServiceProviderStatusEnumProtoZ/micashared/common/enums/serviceproviderstatusv1\242\002\004MICA'
  _SERVICEPROVIDERSTATUS._serialized_start=133
  _SERVICEPROVIDERSTATUS._serialized_end=271
# @@protoc_insertion_point(module_scope)
