# -*- coding: utf-8 -*-
#  Copyright (c) 2024 Mica. All rights reserved. All software, including, without limitation, all source
#  code and object code, is the intellectual property of Mica, Inc. and is protected by copyright, trademark and
#  other intellectual property laws (collective "Mica Software"). You may not use, copy, reproduce, download, store,
#  post, broadcast, transmit, modify, sell or make available to the public content from the Mica Software without a
#  valid license or the prior written approval of Mica, Inc. Mica, its logos, slogans, taglines,
#  products, feature names, and other trademarks are trademarks of Mica, Inc. and may not be used without
#  permission.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mica/serviceprovider/service/v1/service_provider_from_mica_wip_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sdk.mica.common.v1 import currency_pb2 as mica_dot_common_dot_v1_dot_currency__pb2
from sdk.mica.serviceprovider.instrument.v1 import instrument_pb2 as mica_dot_serviceprovider_dot_instrument_dot_v1_dot_instrument__pb2
from sdk.mica.serviceprovider.value.v1 import value_pb2 as mica_dot_serviceprovider_dot_value_dot_v1_dot_value__pb2
from sdk.micashared.common.v1 import error_pb2 as micashared_dot_common_dot_v1_dot_error__pb2
from sdk.micashared.common.v1 import transaction_pb2 as micashared_dot_common_dot_v1_dot_transaction__pb2
from sdk.validate import validate_pb2 as validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLmica/serviceprovider/service/v1/service_provider_from_mica_wip_service.proto\x12\x1fmica.serviceprovider.service.v1\x1a\x1dmica/common/v1/currency.proto\x1a\x33mica/serviceprovider/instrument/v1/instrument.proto\x1a)mica/serviceprovider/value/v1/value.proto\x1a micashared/common/v1/error.proto\x1a&micashared/common/v1/transaction.proto\x1a\x17validate/validate.proto\"\xda\x02\n\x18\x41pproveChargebackRequest\x12\x30\n\x1fservice_provider_instrument_key\x18\x02 \x01(\tB\x07\xfa\x42\x04r\x02\x18\x32\x12p\n\x1dinstrument_external_reference\x18\x16 \x01(\x0b\x32?.mica.serviceprovider.instrument.v1.InstrumentExternalReferenceB\x08\xfa\x42\x05\x8a\x01\x02\x10\x01\x12*\n\x08\x63urrency\x18\x05 \x01(\x0b\x32\x18.mica.common.v1.Currency\x12\x18\n\x10requested_amount\x18\x0f \x01(\t\x12T\n\x1foriginal_transaction_identifier\x18\x13 \x01(\x0b\x32+.micashared.common.v1.TransactionIdentifier\"\xbb\x02\n\x19\x41pproveChargebackResponse\x12Q\n\x06status\x18\x01 \x01(\x0e\x32\x41.mica.serviceprovider.service.v1.ApproveChargebackResponse.Status\x12*\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x1b.micashared.common.v1.Error\x12\'\n\x16\x61pproval_operation_ref\x18\x03 \x01(\tB\x07\xfa\x42\x04r\x02\x18\x64\x12\x0f\n\x07message\x18\x04 \x01(\t\"e\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x18\n\x14STATUS_FULL_APPROVAL\x10\x01\x12\x17\n\x13STATUS_NOT_APPROVED\x10\x02\x12\x10\n\x0cSTATUS_ERROR\x10\x03\x32\xad\x02\n!ServiceProviderFromMicaWIPService\x12\x8c\x01\n\x11\x41pproveChargeback\x12\x39.mica.serviceprovider.service.v1.ApproveChargebackRequest\x1a:.mica.serviceprovider.service.v1.ApproveChargebackResponse\"\x00\x12y\n\x0cReceiveValue\x12\x32.mica.serviceprovider.value.v1.ReceiveValueRequest\x1a\x33.mica.serviceprovider.value.v1.ReceiveValueResponse\"\x00\x42s\n\"io.mica.serviceprovider.service.v1B&ServiceProviderFromMicaWIPServiceProtoZ\x1emica/serviceprovider/servicev1\xa2\x02\x04MICAb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mica.serviceprovider.service.v1.service_provider_from_mica_wip_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\"io.mica.serviceprovider.service.v1B&ServiceProviderFromMicaWIPServiceProtoZ\036mica/serviceprovider/servicev1\242\002\004MICA'
  _APPROVECHARGEBACKREQUEST.fields_by_name['service_provider_instrument_key']._options = None
  _APPROVECHARGEBACKREQUEST.fields_by_name['service_provider_instrument_key']._serialized_options = b'\372B\004r\002\0302'
  _APPROVECHARGEBACKREQUEST.fields_by_name['instrument_external_reference']._options = None
  _APPROVECHARGEBACKREQUEST.fields_by_name['instrument_external_reference']._serialized_options = b'\372B\005\212\001\002\020\001'
  _APPROVECHARGEBACKRESPONSE.fields_by_name['approval_operation_ref']._options = None
  _APPROVECHARGEBACKRESPONSE.fields_by_name['approval_operation_ref']._serialized_options = b'\372B\004r\002\030d'
  _APPROVECHARGEBACKREQUEST._serialized_start=340
  _APPROVECHARGEBACKREQUEST._serialized_end=686
  _APPROVECHARGEBACKRESPONSE._serialized_start=689
  _APPROVECHARGEBACKRESPONSE._serialized_end=1004
  _APPROVECHARGEBACKRESPONSE_STATUS._serialized_start=903
  _APPROVECHARGEBACKRESPONSE_STATUS._serialized_end=1004
  _SERVICEPROVIDERFROMMICAWIPSERVICE._serialized_start=1007
  _SERVICEPROVIDERFROMMICAWIPSERVICE._serialized_end=1308
# @@protoc_insertion_point(module_scope)
