# -*- coding: utf-8 -*-
#  Copyright (c) 2022 Mica. All rights reserved. All software, including, without limitation, all source 
#  code and object code, is the intellectual property of Mica, Inc. and is protected by copyright, trademark and 
#  other intellectual property laws (collective "Mica Software"). You may not use, copy, reproduce, download, store, 
#  post, broadcast, transmit, modify, sell or make available to the public content from the Mica Software without a 
#  valid license or the prior written approval of Mica, Inc. Mica, its logos, slogans, taglines, 
#  products, feature names, and other trademarks are trademarks of Mica, Inc. and may not be used without 
#  permission.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/enums/realm/v1/realm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!common/enums/realm/v1/realm.proto\x12\x15\x63ommon.enums.realm.v1*R\n\x05Realm\x12\x15\n\x11REALM_UNSPECIFIED\x10\x00\x12\x0f\n\x0bREALM_ADMIN\x10\x01\x12\x11\n\rREALM_SERVICE\x10\x02\x12\x0e\n\nREALM_USER\x10\x03\x42Q\n\x17io.mica.common.enums.v1B\x0eRealmEnumProtoZ\x1fmica/proto/common/enums/realmv1\xa2\x02\x04MICAb\x06proto3')

_REALM = DESCRIPTOR.enum_types_by_name['Realm']
Realm = enum_type_wrapper.EnumTypeWrapper(_REALM)
REALM_UNSPECIFIED = 0
REALM_ADMIN = 1
REALM_SERVICE = 2
REALM_USER = 3


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027io.mica.common.enums.v1B\016RealmEnumProtoZ\037mica/proto/common/enums/realmv1\242\002\004MICA'
  _REALM._serialized_start=60
  _REALM._serialized_end=142
# @@protoc_insertion_point(module_scope)
