# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connect/service/v1/connect_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mica.connect.instrument.v1 import instrument_pb2 as connect_dot_instrument_dot_v1_dot_instrument__pb2
from mica.common.ping.v1 import ping_pb2 as common_dot_ping_dot_v1_dot_ping__pb2
from mica.connect.staticdata.v1 import static_data_pb2 as connect_dot_staticdata_dot_v1_dot_static__data__pb2
from mica.connect.serviceprovider.v1 import service_provider_pb2 as connect_dot_serviceprovider_dot_v1_dot_service__provider__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='connect/service/v1/connect_service.proto',
  package='connect.service.v1',
  syntax='proto3',
  serialized_options=b'Z\035ten80/proto/connect/servicev1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(connect/service/v1/connect_service.proto\x12\x12\x63onnect.service.v1\x1a&connect/instrument/v1/instrument.proto\x1a\x19\x63ommon/ping/v1/ping.proto\x1a\'connect/staticdata/v1/static_data.proto\x1a\x31\x63onnect/serviceprovider/v1/service_provider.proto2\x8f\x08\n\x0e\x43onnectService\x12l\n\rGetStaticData\x12+.connect.staticdata.v1.GetStaticDataRequest\x1a,.connect.staticdata.v1.GetStaticDataResponse\"\x00\x12\x8e\x01\n\x15SearchServiceProvider\x12\x38.connect.serviceprovider.v1.SearchServiceProviderRequest\x1a\x39.connect.serviceprovider.v1.SearchServiceProviderResponse\"\x00\x12\xa5\x01\n WidgetRegisterInstrumentInitiate\x12>.connect.instrument.v1.WidgetRegisterInstrumentInitiateRequest\x1a?.connect.instrument.v1.WidgetRegisterInstrumentInitiateResponse\"\x00\x12\xae\x01\n#WidgetRegisterInstrumentWithAccount\x12\x41.connect.instrument.v1.WidgetRegisterInstrumentWithAccountRequest\x1a\x42.connect.instrument.v1.WidgetRegisterInstrumentWithAccountResponse\"\x00\x12\xa5\x01\n WidgetRegisterInstrumentComplete\x12>.connect.instrument.v1.WidgetRegisterInstrumentCompleteRequest\x1a?.connect.instrument.v1.WidgetRegisterInstrumentCompleteResponse\"\x00\x12\xb7\x01\n&WidgetRibbitRegisterInstrumentInitiate\x12\x44.connect.instrument.v1.WidgetRibbitRegisterInstrumentInitiateRequest\x1a\x45.connect.instrument.v1.WidgetRibbitRegisterInstrumentInitiateResponse\"\x00\x12\x43\n\x04Ping\x12\x1b.common.ping.v1.PingRequest\x1a\x1c.common.ping.v1.PingResponse\"\x00\x42\x1fZ\x1dten80/proto/connect/servicev1b\x06proto3'
  ,
  dependencies=[connect_dot_instrument_dot_v1_dot_instrument__pb2.DESCRIPTOR,common_dot_ping_dot_v1_dot_ping__pb2.DESCRIPTOR,connect_dot_staticdata_dot_v1_dot_static__data__pb2.DESCRIPTOR,connect_dot_serviceprovider_dot_v1_dot_service__provider__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_CONNECTSERVICE = _descriptor.ServiceDescriptor(
  name='ConnectService',
  full_name='connect.service.v1.ConnectService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=224,
  serialized_end=1263,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetStaticData',
    full_name='connect.service.v1.ConnectService.GetStaticData',
    index=0,
    containing_service=None,
    input_type=connect_dot_staticdata_dot_v1_dot_static__data__pb2._GETSTATICDATAREQUEST,
    output_type=connect_dot_staticdata_dot_v1_dot_static__data__pb2._GETSTATICDATARESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SearchServiceProvider',
    full_name='connect.service.v1.ConnectService.SearchServiceProvider',
    index=1,
    containing_service=None,
    input_type=connect_dot_serviceprovider_dot_v1_dot_service__provider__pb2._SEARCHSERVICEPROVIDERREQUEST,
    output_type=connect_dot_serviceprovider_dot_v1_dot_service__provider__pb2._SEARCHSERVICEPROVIDERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WidgetRegisterInstrumentInitiate',
    full_name='connect.service.v1.ConnectService.WidgetRegisterInstrumentInitiate',
    index=2,
    containing_service=None,
    input_type=connect_dot_instrument_dot_v1_dot_instrument__pb2._WIDGETREGISTERINSTRUMENTINITIATEREQUEST,
    output_type=connect_dot_instrument_dot_v1_dot_instrument__pb2._WIDGETREGISTERINSTRUMENTINITIATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WidgetRegisterInstrumentWithAccount',
    full_name='connect.service.v1.ConnectService.WidgetRegisterInstrumentWithAccount',
    index=3,
    containing_service=None,
    input_type=connect_dot_instrument_dot_v1_dot_instrument__pb2._WIDGETREGISTERINSTRUMENTWITHACCOUNTREQUEST,
    output_type=connect_dot_instrument_dot_v1_dot_instrument__pb2._WIDGETREGISTERINSTRUMENTWITHACCOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WidgetRegisterInstrumentComplete',
    full_name='connect.service.v1.ConnectService.WidgetRegisterInstrumentComplete',
    index=4,
    containing_service=None,
    input_type=connect_dot_instrument_dot_v1_dot_instrument__pb2._WIDGETREGISTERINSTRUMENTCOMPLETEREQUEST,
    output_type=connect_dot_instrument_dot_v1_dot_instrument__pb2._WIDGETREGISTERINSTRUMENTCOMPLETERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WidgetRibbitRegisterInstrumentInitiate',
    full_name='connect.service.v1.ConnectService.WidgetRibbitRegisterInstrumentInitiate',
    index=5,
    containing_service=None,
    input_type=connect_dot_instrument_dot_v1_dot_instrument__pb2._WIDGETRIBBITREGISTERINSTRUMENTINITIATEREQUEST,
    output_type=connect_dot_instrument_dot_v1_dot_instrument__pb2._WIDGETRIBBITREGISTERINSTRUMENTINITIATERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='connect.service.v1.ConnectService.Ping',
    index=6,
    containing_service=None,
    input_type=common_dot_ping_dot_v1_dot_ping__pb2._PINGREQUEST,
    output_type=common_dot_ping_dot_v1_dot_ping__pb2._PINGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONNECTSERVICE)

DESCRIPTOR.services_by_name['ConnectService'] = _CONNECTSERVICE

# @@protoc_insertion_point(module_scope)
