# -*- coding: utf-8 -*-
#  Copyright (c) 2022 Mica. All rights reserved. All software, including, without limitation, all source #  code and object code, is the intellectual property of Mica, Inc. and is protected by copyright, trademark and #  other intellectual property laws (collective "Mica Software"). You may not use, copy, reproduce, download, store, #  post, broadcast, transmit, modify, sell or make available to the public content from the Mica Software without a #  valid license or the prior written approval of Mica, Inc. Mica, its logos, slogans, taglines, #  products, feature names, and other trademarks are trademarks of Mica, Inc. and may not be used without #  permission.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/enums/lineitemstatus/v1/line_item_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5common/enums/lineitemstatus/v1/line_item_status.proto\x12\x1e\x63ommon.enums.lineitemstatus.v1*\xba\x01\n\x0eLineItemStatus\x12 \n\x1cLINE_ITEM_STATUS_UNSPECIFIED\x10\x00\x12!\n\x1dLINE_ITEM_STATUS_NOT_ASSESSED\x10\x01\x12\x1d\n\x19LINE_ITEM_STATUS_ELIGIBLE\x10\x02\x12\x1f\n\x1bLINE_ITEM_STATUS_INELIGIBLE\x10\x03\x12#\n\x1fLINE_ITEM_STATUS_AGE_RESTRICTED\x10\x04\x42\x63\n\x17io.mica.common.enums.v1B\x17LineItemStatusEnumProtoZ(mica/proto/common/enums/lineitemstatusv1\xa2\x02\x04MICAb\x06proto3')

_LINEITEMSTATUS = DESCRIPTOR.enum_types_by_name['LineItemStatus']
LineItemStatus = enum_type_wrapper.EnumTypeWrapper(_LINEITEMSTATUS)
LINE_ITEM_STATUS_UNSPECIFIED = 0
LINE_ITEM_STATUS_NOT_ASSESSED = 1
LINE_ITEM_STATUS_ELIGIBLE = 2
LINE_ITEM_STATUS_INELIGIBLE = 3
LINE_ITEM_STATUS_AGE_RESTRICTED = 4


if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027io.mica.common.enums.v1B\027LineItemStatusEnumProtoZ(mica/proto/common/enums/lineitemstatusv1\242\002\004MICA'
  _LINEITEMSTATUS._serialized_start=90
  _LINEITEMSTATUS._serialized_end=276
# @@protoc_insertion_point(module_scope)
