# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from mica.discount.service.v1 import discount_service_test_support_pb2 as mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2


class DiscountTestSupportServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestDetermineDiscount = channel.unary_unary(
                '/mica.discount.service.v1.DiscountTestSupportService/TestDetermineDiscount',
                request_serializer=mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.DetermineDiscountRequest.SerializeToString,
                response_deserializer=mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.DetermineDiscountResponse.FromString,
                )
        self.TestApplyDiscount = channel.unary_unary(
                '/mica.discount.service.v1.DiscountTestSupportService/TestApplyDiscount',
                request_serializer=mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.ApplyDiscountRequest.SerializeToString,
                response_deserializer=mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.ApplyDiscountResponse.FromString,
                )
        self.TestReleaseDiscount = channel.unary_unary(
                '/mica.discount.service.v1.DiscountTestSupportService/TestReleaseDiscount',
                request_serializer=mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.ReleaseDiscountRequest.SerializeToString,
                response_deserializer=mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.ReleaseDiscountResponse.FromString,
                )


class DiscountTestSupportServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TestDetermineDiscount(self, request, context):
        """Determine which discount(s) can be applied to this transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestApplyDiscount(self, request, context):
        """Apply or release a given discount
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestReleaseDiscount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscountTestSupportServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TestDetermineDiscount': grpc.unary_unary_rpc_method_handler(
                    servicer.TestDetermineDiscount,
                    request_deserializer=mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.DetermineDiscountRequest.FromString,
                    response_serializer=mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.DetermineDiscountResponse.SerializeToString,
            ),
            'TestApplyDiscount': grpc.unary_unary_rpc_method_handler(
                    servicer.TestApplyDiscount,
                    request_deserializer=mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.ApplyDiscountRequest.FromString,
                    response_serializer=mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.ApplyDiscountResponse.SerializeToString,
            ),
            'TestReleaseDiscount': grpc.unary_unary_rpc_method_handler(
                    servicer.TestReleaseDiscount,
                    request_deserializer=mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.ReleaseDiscountRequest.FromString,
                    response_serializer=mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.ReleaseDiscountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mica.discount.service.v1.DiscountTestSupportService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DiscountTestSupportService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TestDetermineDiscount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mica.discount.service.v1.DiscountTestSupportService/TestDetermineDiscount',
            mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.DetermineDiscountRequest.SerializeToString,
            mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.DetermineDiscountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestApplyDiscount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mica.discount.service.v1.DiscountTestSupportService/TestApplyDiscount',
            mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.ApplyDiscountRequest.SerializeToString,
            mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.ApplyDiscountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestReleaseDiscount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mica.discount.service.v1.DiscountTestSupportService/TestReleaseDiscount',
            mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.ReleaseDiscountRequest.SerializeToString,
            mica_dot_discount_dot_service_dot_v1_dot_discount__service__test__support__pb2.ReleaseDiscountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
