# -*- coding: utf-8 -*-
#  Copyright (c) 2023 Mica. All rights reserved. All software, including, without limitation, all source
#  code and object code, is the intellectual property of Mica, Inc. and is protected by copyright, trademark and
#  other intellectual property laws (collective "Mica Software"). You may not use, copy, reproduce, download, store,
#  post, broadcast, transmit, modify, sell or make available to the public content from the Mica Software without a
#  valid license or the prior written approval of Mica, Inc. Mica, its logos, slogans, taglines,
#  products, feature names, and other trademarks are trademarks of Mica, Inc. and may not be used without
#  permission.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: micashared/common/v1/error.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n micashared/common/v1/error.proto\x12\x14micashared.common.v1\"P\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0b\n\x03\x63id\x18\x02 \x01(\t\x12\x14\n\x0cservice_type\x18\x03 \x01(\t\x12\x13\n\x0b\x66ull_method\x18\x04 \x01(\tBK\n\x17io.micashared.common.v1B\nErrorProtoZ\x1dmicashared/common/v1;commonv1\xa2\x02\x04MICAb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'micashared.common.v1.error_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027io.micashared.common.v1B\nErrorProtoZ\035micashared/common/v1;commonv1\242\002\004MICA'
  _ERROR._serialized_start=58
  _ERROR._serialized_end=138
# @@protoc_insertion_point(module_scope)
