# -*- coding: utf-8 -*-
#  Copyright (c) 2024 Mica. All rights reserved. All software, including, without limitation, all source
#  code and object code, is the intellectual property of Mica, Inc. and is protected by copyright, trademark and
#  other intellectual property laws (collective "Mica Software"). You may not use, copy, reproduce, download, store,
#  post, broadcast, transmit, modify, sell or make available to the public content from the Mica Software without a
#  valid license or the prior written approval of Mica, Inc. Mica, its logos, slogans, taglines,
#  products, feature names, and other trademarks are trademarks of Mica, Inc. and may not be used without
#  permission.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: micashared/common/v1/uuek.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmicashared/common/v1/uuek.proto\x12\x14micashared.common.v1\"0\n\x1aImmutableInstrumentDetails\x12\x12\n\nidentifier\x18\x01 \x01(\tBJ\n\x17io.micashared.common.v1B\tUUEKProtoZ\x1dmicashared/common/v1;commonv1\xa2\x02\x04MICAb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'micashared.common.v1.uuek_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027io.micashared.common.v1B\tUUEKProtoZ\035micashared/common/v1;commonv1\242\002\004MICA'
  _IMMUTABLEINSTRUMENTDETAILS._serialized_start=57
  _IMMUTABLEINSTRUMENTDETAILS._serialized_end=105
# @@protoc_insertion_point(module_scope)
