# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/v1/organization.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mica.common.v1 import address_pb2 as common_dot_v1_dot_address__pb2
from mica.common.enums.organizationcategory.v1 import organization_category_pb2 as common_dot_enums_dot_organizationcategory_dot_v1_dot_organization__category__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='common/v1/organization.proto',
  package='common.v1',
  syntax='proto3',
  serialized_options=b'\n\027network.ten80.common.v1B\021OrganizationProtoZ\036ten80/proto/common/v1;commonv1\242\002\005TEN80',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1c\x63ommon/v1/organization.proto\x12\tcommon.v1\x1a\x17\x63ommon/v1/address.proto\x1a@common/enums/organizationcategory/v1/organization_category.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc1\x03\n\x0cOrganization\x12\x18\n\x10organization_key\x18\x01 \x01(\t\x12+\n\x07\x63reated\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07updated\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bpartner_key\x18\x04 \x01(\t\x12\x0c\n\x04name\x18\x06 \x01(\t\x12N\n\ncategories\x18\x05 \x03(\x0e\x32:.common.enums.organizationcategory.v1.OrganizationCategory\x12#\n\x07\x61\x64\x64ress\x18\x08 \x01(\x0b\x32\x12.common.v1.Address\x12#\n\x1b\x64omestic_ach_routing_number\x18\t \x01(\t\x12(\n international_ach_routing_number\x18\n \x01(\t\x12\x1b\n\x13wire_routing_number\x18\x0b \x01(\t\x12\x1c\n\x14swift_routing_number\x18\x0c \x01(\t\x12\x1b\n\x13\x62\x61nk_account_number\x18\r \x01(\tBT\n\x17network.ten80.common.v1B\x11OrganizationProtoZ\x1eten80/proto/common/v1;commonv1\xa2\x02\x05TEN80b\x06proto3'
  ,
  dependencies=[common_dot_v1_dot_address__pb2.DESCRIPTOR,common_dot_enums_dot_organizationcategory_dot_v1_dot_organization__category__pb2.DESCRIPTOR,google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_ORGANIZATION = _descriptor.Descriptor(
  name='Organization',
  full_name='common.v1.Organization',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='organization_key', full_name='common.v1.Organization.organization_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created', full_name='common.v1.Organization.created', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updated', full_name='common.v1.Organization.updated', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='partner_key', full_name='common.v1.Organization.partner_key', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='common.v1.Organization.name', index=4,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='categories', full_name='common.v1.Organization.categories', index=5,
      number=5, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='common.v1.Organization.address', index=6,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='domestic_ach_routing_number', full_name='common.v1.Organization.domestic_ach_routing_number', index=7,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='international_ach_routing_number', full_name='common.v1.Organization.international_ach_routing_number', index=8,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wire_routing_number', full_name='common.v1.Organization.wire_routing_number', index=9,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='swift_routing_number', full_name='common.v1.Organization.swift_routing_number', index=10,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bank_account_number', full_name='common.v1.Organization.bank_account_number', index=11,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=617,
)

_ORGANIZATION.fields_by_name['created'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ORGANIZATION.fields_by_name['updated'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_ORGANIZATION.fields_by_name['categories'].enum_type = common_dot_enums_dot_organizationcategory_dot_v1_dot_organization__category__pb2._ORGANIZATIONCATEGORY
_ORGANIZATION.fields_by_name['address'].message_type = common_dot_v1_dot_address__pb2._ADDRESS
DESCRIPTOR.message_types_by_name['Organization'] = _ORGANIZATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Organization = _reflection.GeneratedProtocolMessageType('Organization', (_message.Message,), {
  'DESCRIPTOR' : _ORGANIZATION,
  '__module__' : 'common.v1.organization_pb2'
  # @@protoc_insertion_point(class_scope:common.v1.Organization)
  })
_sym_db.RegisterMessage(Organization)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
