# -*- coding: utf-8 -*-
#  Copyright (c) 2024 Mica. All rights reserved. All software, including, without limitation, all source
#  code and object code, is the intellectual property of Mica, Inc. and is protected by copyright, trademark and
#  other intellectual property laws (collective "Mica Software"). You may not use, copy, reproduce, download, store,
#  post, broadcast, transmit, modify, sell or make available to the public content from the Mica Software without a
#  valid license or the prior written approval of Mica, Inc. Mica, its logos, slogans, taglines,
#  products, feature names, and other trademarks are trademarks of Mica, Inc. and may not be used without
#  permission.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: micashared/common/enums/custodialbank/v1/custodial_bank.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=micashared/common/enums/custodialbank/v1/custodial_bank.proto\x12(micashared.common.enums.custodialbank.v1*q\n\rCustodialBank\x12\x1e\n\x1a\x43USTODIAL_BANK_UNSPECIFIED\x10\x00\x12\x1c\n\x18\x43USTODIAL_BANK_TEST_BANK\x10\x01\x12\"\n\x1e\x43USTODIAL_BANK_MAINSTREET_BANK\x10\x02\x42g\n\x1dio.micashared.common.enums.v1B\x16\x43ustodialBankEnumProtoZ\'micashared/common/enums/custodialbankv1\xa2\x02\x04MICAb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'micashared.common.enums.custodialbank.v1.custodial_bank_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035io.micashared.common.enums.v1B\026CustodialBankEnumProtoZ\'micashared/common/enums/custodialbankv1\242\002\004MICA'
  _CUSTODIALBANK._serialized_start=107
  _CUSTODIALBANK._serialized_end=220
# @@protoc_insertion_point(module_scope)
