# -*- coding: utf-8 -*-
#  Copyright (c) 2022 Mica. All rights reserved. All software, including, without limitation, all source #  code and object code, is the intellectual property of Mica, Inc. and is protected by copyright, trademark and #  other intellectual property laws (collective "Mica Software"). You may not use, copy, reproduce, download, store, #  post, broadcast, transmit, modify, sell or make available to the public content from the Mica Software without a #  valid license or the prior written approval of Mica, Inc. Mica, its logos, slogans, taglines, #  products, feature names, and other trademarks are trademarks of Mica, Inc. and may not be used without #  permission.
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: partner/service/v1/partner_from_mica_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from micapartner.common.ping.v1 import ping_pb2 as common_dot_ping_dot_v1_dot_ping__pb2
from micapartner.partner.user.v1 import user_pb2 as partner_dot_user_dot_v1_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2partner/service/v1/partner_from_mica_service.proto\x12\x12partner.service.v1\x1a\x19\x63ommon/ping/v1/ping.proto\x1a\x1apartner/user/v1/user.proto2\xd4\x01\n\x16PartnerFromMicaService\x12u\n\x14\x45nrollUserInstrument\x12,.partner.user.v1.EnrollUserInstrumentRequest\x1a-.partner.user.v1.EnrollUserInstrumentResponse\"\x00\x12\x43\n\x04Ping\x12\x1b.common.ping.v1.PingRequest\x1a\x1c.common.ping.v1.PingResponse\"\x00\x42^\n\x1aio.mica.partner.service.v1B\x1bPartnerFromMicaServiceProtoZ\x1cmica/proto/partner/servicev1\xa2\x02\x04MICAb\x06proto3')



_PARTNERFROMMICASERVICE = DESCRIPTOR.services_by_name['PartnerFromMicaService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032io.mica.partner.service.v1B\033PartnerFromMicaServiceProtoZ\034mica/proto/partner/servicev1\242\002\004MICA'
  _PARTNERFROMMICASERVICE._serialized_start=130
  _PARTNERFROMMICASERVICE._serialized_end=342
# @@protoc_insertion_point(module_scope)
